# Generated by Django 5.2 on 2025-05-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_id', models.CharField(max_length=100)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
