# Generated by Django 5.2 on 2025-05-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
